version: '3'
services:
  api:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend/pianotutor:/backend/pianotutor
      - db:/backend/instance
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=/api/app.py
      - FLASK_DEBUG=1
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules # make sure we don't overwrite the installed node_modules with the previous bind mount
volumes:
  db: