version: '3'
services:
  api:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./api:/api
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=/api/app.py
      - FLASK_DEBUG=1
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app